package com.yk.demo.wan.dmnd.entity

data class Work(
    val deptName :String,
    val productForm:String,
    val drank:String,
    val isDelete:String,
    val appNo:String,
    val dtype:String,
    val updateTime:String,
    val dpurpose:String,
    val userName:String,
    val type:String,
    val userId:String,
    val deptNo:String,
    val technicalRequirement:String,
    val dstage:String,
    val createTime:String,
    val isOver:String,
    val startTime:String,
    val id:Long,
    val endTime:String,
    val remark:String,
    val sysUser:String,
    val demandDescription:String,
    val status:String,
    val state:String,
    val modular:String,
    val modulartwo:String,
    val hopeTime:String,
    val overdue:String,
    val estimatedTime:String,
    val overdueDay:String,
    val overdueDayNow:String,
    val address:String,
    val demandClassify:String,
    val problemDescription:String,
    val problemAnalysis:String,
    val version:String
)